name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false
        poetry install

    # - name: Run Type Checks
    #   run: poetry run mypy type-fastapi/

    # - name: Run Tests
    #   run: poetry run pytest

    - name: Build Package
      run: poetry build

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry config pypi-token.pypi $PYPI_TOKEN
      run: poetry publish --build 
