name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Use the Python version supported by your project

      # Step 3: Install Poetry
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      # Step 5: Run all test cases with coverage check
      - name: Run Tests with Coverage Threshold
        run: |
          poetry run pytest --cov=tests/ --cov-fail-under=90